[unstable]
codegen-backend = true

[profile.dev]
opt-level = "s"
codegen-backend = "cranelift"
incremental = true
rustflags = [
    "-Zthreads=0",
]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
panic = "unwind"
strip = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=lld",
]
rustdocflags = [
    "-Clink-arg=-fuse-ld=lld",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
